home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    #uso livre.
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),

    path('monitorias/', views.monitoria, name='monitorias'),
    path('monitorias/search/', views.search_monitoria, name='search'),
    path('monitorias/update/<int:id>/', views.update_monitoria, name='update_monitoria'),

    #o usuário pode acessar.
    path('update/', views.update, name='update'),
    path('update/password/', views.password, name='password'),
    path('marcar_monitoria/', views.marcar_monitoria, name='marcar_monitoria'),

    #somente o super-user pode acessá-lo.
    path('data/', views.dados, name='dados'),
    path('config/', views.config, name='config'),
    path('config/search/', views.search_config, name='search_config'),
    path('config/update-days/', views.update_days, name='update_days'),
    path('config/update-hours/', views.update_hours, name='update_hours'),
    path('config/matricula/', views.matricula, name='matricula'),
    path('config/matricula/create', views.create, name='create'),
    path('config/matricula/update', views.update_matricula, name='update_matricula'),
    path('config/matricula/delete', views.delete_matricula, name='delete_matricula'),
    path('config/usuarios', views.usuarios, name='usuarios'),
    path('config/usuarios/search', views.search_usuarios, name='search_usuarios'),    
    path('config/usuarios/update', views.update_usuarios, name='update_usuarios'),
]


#TODO: 
# ------------OK 1 - disponibilizar o delete da conta do próprio usuário.


# ------------OK 2 - Montar view para expor ao usuário os dias que a monitoria pode ser marcada.
# ------------OK 5 - inserir o filtro de dados datetime.now para o search_monitorias
# ------------OK 6 - retirar o aside para o admin
# ------------OK 8 - disponibilizar para o usuário somente os dias da semana que ele possui marcação de horario na tabela monitoria;
# ------------OK 9 - requerer login para a view monitoria
# ------------OK 10 - admin não pode marcar monitoria, alterar o aside, mostrar todas as monitoria marcadas para hoje no aside  


# ------------OK 3 - atualizar o model de DataUser: inserir o atributo monitorias_ausentes
# ------------OK 11 - add telefone ao campo de updates
# 12 - add telefone ao campo de cadastro

# ------------OK 13 - add status ao models Monitorias
# ------------OK 14 - add alteração de status para as monitorias do dia e antepassadas
# 15 - vincular os campos de datauser ao models monitoria
# 16 - alterar a view update_monitorias para realizar o TODO n° 14
# 7 - inserir regra de negócio: mais de 3 moonitorias ausentes sem aviso prévio, o usuario será suspenso do sistema
# 17 - Refatorar o cadastro
# 18 - Inserir o campo de recuperar senha
# 19 - add hora ao marcar monitoria
# ------------OK 20 - ao criar o cadastro, criar o datauser

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls'), name='home'),    
]

home/views/cadastro.py
from django.shortcuts import render, redirect
from home.forms.update_create_form import CreateForm
from home.views import message
from home.models import DataUser, Matriculas
def cadastro(request):

    if request.method == 'POST':
        form = CreateForm(
            request.POST
        )
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            data_user = DataUser(owner=user)
            data_user.phone = form.cleaned_data['phone']
            data_user.save()
            matricula = Matriculas.objects.get(
                matricula=form.cleaned_data['username']
            )
            matricula.status = True
            matricula.save()

            form.save()
            message(request, 'Cadastro realizado com sucesso!', sucesss=True)
            return redirect('home:home')
        message(request, 'Atente-se aos requisitos!!!')
        context = {
        'title': 'Cadastro',
        'form': form,
        }
        url = 'home/cadastro.html'
        return render(request, url, context=context)

home/views/config.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from home.models import DataUser, Horas, Days
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from home.views.index import message
from home.views.index import daysweek

@login_required(login_url="home:home")
def update_hours(request):
    day = request.POST.get('daysweek', '').strip()
    time_start = request.POST.get('time_start', '').strip()
    time_end = request.POST.get('time_end', '').strip()
    if not day or not time_start or not time_end:
        message(request, 'Preencha todos os campos', error=True)
        return redirect('home:config')
    try:
        day = Days.objects.get(day=day)
    except Days.DoesNotExist:
        message(request, 'Dia não encontrado', error=True)
        return redirect('home:config')
    try:
        horas = Horas.objects.filter(
        day__day=day
        )
        for hora in horas:
            hora.delete()
    except Horas.DoesNotExist:
        ...
        
    horas_start = Horas(
        day=day,
        time=time_start
    )
    horas_start.save()
    horas_final = Horas(
        day=day,
        time=time_end
    )
    horas_final.save()
    return redirect('home:config')

@login_required(login_url="home:home")
def update_days(request):
    days = request.POST
    dias_cadastrados = Days.objects.all()
    dias_cadastrados.delete()
    time_start = request.POST.get('time_start', '07:00:00').strip()
    time_end = request.POST.get('time_end', '12:00:00').strip()
    for key, value in days.items():
        if key == 'csrfmiddlewaretoken':
            continue
        day = Days(day=value)
        day.save()
        horas_start = Horas(
            day=day,
            time=time_start
        )
        horas_start.save()
        horas_final = Horas(
            day=day,
            time=time_end
        )
        horas_final.save()
    return redirect('home:config')

@login_required(login_url="home:home") 
def search_config(request):

    search_value = str(request.GET.get('q', '')).strip()
    if not search_value:
        redirect('home:config')

    data_user = DataUser.objects.filter(
        Q(owner__username__icontains=search_value) |
        Q(owner__first_name__icontains=search_value) |
        Q(owner__last_name__icontains=search_value)
    )
    days = Days.objects.all()
    horas = Horas.objects.all().order_by('day')
    data = [{
        "usuario": user.owner, 
        "monitorias_presentes": user.monitorias_presentes, 
        "monitorias_marcadas": user.monitorias_marcadas} 
        for user in data_user if user.is_superuser == False
        ]
    hr = [
        {"time": h.time, "day": h.day.day} 
        for h in horas
        ]
    pagination = Paginator(data, 10)
    page_number = request.GET.get("page")
    data = pagination.get_page(page_number)
    context = {
        'title': f'Configurações-{search_value}',
        'data': data,
        'search': search_value,
        'daysweek': daysweek,
        'days': [str(dia).strip() for dia in days],
        'horas': hr,
    }
    url = 'home/config.html'
    return render(request, url, context=context)

@login_required(login_url="home:home") 
def config(request):

    data_user = DataUser.objects.all()
    days = Days.objects.all()

    horas = Horas.objects.all().order_by('day')
    data = [{
        "usuario": user.owner, 
        "monitorias_presentes": user.monitorias_presentes, 
        "monitorias_marcadas": user.monitorias_marcadas} 
        for user in data_user if user.owner.is_superuser == False
        ]
    hr = [{"time": h.time, "day": h.day.day} for h in horas]

    pagination = Paginator(data, 10)
    page_number = request.GET.get("page")
    data = pagination.get_page(page_number)

    context = {
        'title': 'Configurações',
        'data': data,
        'daysweek': daysweek,
        'days': [str(dia).strip() for dia in days],
        'horas': hr,
    }
    
    url = 'home/config.html'
    return render(request, url, context=context)

home/views/dados.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from home.models import User
from datetime import datetime
from django.db.models import Q
from django.core.paginator import Paginator

def dados(request):

    context = {
        'title': 'Estatísticas',
        'data': [],
    }
    url = 'home/data.html'
    return render(request, url, context=context)

home/views/index.py
from django.shortcuts import render
from home.models import Monitorias, Horas
from django.db.models import Q
from itertools import groupby
daysweek = [
    'Segunda-feira',
    'Terça-feira',
    'Quarta-feira',
    'Quinta-feira',
    'Sexta-feira',
]

LIM_PART_MONITORIA = 5

def monitorias_marcadas_usuario(user):
    import datetime
    from datetime import timedelta, datetime
    data = Monitorias.objects.filter(
        Q(owner=user) & 
        Q(status__icontains='Marcada') &
        Q(date__range=(
            datetime.now(), 
            datetime.now() + timedelta(days=7)
            )
        )
    )
    return data

def monitorias_marcadas_monitor():
    import datetime
    from datetime import datetime 
    data = Monitorias.objects.filter(
        Q(date__range=(datetime.now(), datetime.now())) &
        Q(status__icontains='Marcada')
    )
    return data

def free_days_next_monitorias():
    import datetime
    from datetime import datetime, timedelta
    data = Monitorias.objects.filter(
        Q(date__range=(datetime.now() + timedelta(1), datetime.now() + timedelta(days=7))) &
        Q(status__icontains='Marcada')

        )
    monitorias = groupby(sorted([
        {'date': item.date, 'user': item.owner.username} for item in data], key=lambda date: date['date']
        ), key=lambda date: date['date'])
    
    daysweek_monitoria = [daysweek.index(day['dayweek']) for day in days()]
    next_seven_days = set([
        (datetime.now() + timedelta(days=i)).date() 
        for i in range(1, 8) 
        if (datetime.now() + timedelta(days=i)).weekday() in daysweek_monitoria
        ])
    monitorias = set([item[0] for item in monitorias 
                  if len(list(item[1])) >= LIM_PART_MONITORIA
                  and item[0].weekday() in daysweek_monitoria
                  ])
    monitorias = sorted(list(next_seven_days - monitorias))
    return monitorias
    
def message(request, msg: str, sucesss=False, error=False):
    from django.contrib import messages
    if sucesss:
        return messages.success(request, msg)
    if error:
        return messages.error(request, msg)

    return messages.warning(request=request, message=msg)

def days():
    horarios = Horas.objects.all()
    weekday = {}
    data = [{"hora": item.time, 'day': item.day.day} for item in horarios]
    for item in data:
        if item['day'] not in weekday.keys():
            weekday[item['day']] = [item['hora']]
            continue
        weekday[item['day']].append(item['hora'])
    data = [{"dayweek": key, "time_start": str(value[0]), "time_final": str(value[-1])} for key, value in weekday.items()]
    return data

def index(request):

    context = {
        'title': 'HOME',
        'horarios': days(),
    }
    url = 'home/index.html'
    return render(request, url, context=context)

home/views/login.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from home.forms.login import Login
from home.forms.update_create_form import CreateForm
from django.contrib.auth.models import User
from django.db.models import Q
from home.models import DataUser, Matriculas
from home.views import days, message
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth 
from django.contrib.auth.decorators import login_required

def login(request):
    
    matricula = str(request.POST.get('matricula', '')).strip()
    password = request.POST.get('password', '')
    if password:
        form_auth = AuthenticationForm(
            request, data=request.POST)
        form = Login(
            matricula,
            request.POST
        )
        if form_auth.is_valid():
            user = form_auth.get_user()
            auth.login(request, user)
            message(request, 'Login realizado', sucesss=True)
            context = {
            'title': 'Home',
            'horarios': days(),
            'form': form,
            }
            url = 'home/index.html'
            return render(request, url, context=context)
        
        message(request, 'Login inválido, seu usuário pode estar inativo', error=True)
        context = {
            'title': 'login',
            'horarios': days(),
            'form': form,
        }
        url = 'home/login.html'
        return render(request, url, context=context)

    if len(matricula) != 12:
        message(request, 'Matrícula inválida', error=True)
        return redirect('home:home')

    if matricula:

        try:
            matriculas_cadastradas = Matriculas.objects.get(matricula = matricula)
        except Matriculas.DoesNotExist:
            matriculas_cadastradas = None
        
        try:
            user = User.objects.get(username= matricula)
            if not user.is_active:
                message(request, 'Usuário inativo', error=True)
                return redirect('home:home')    
        except User.DoesNotExist:
            user = None
        
        if not matriculas_cadastradas and not user:
            msg ='Não foi possível encontrar sua matrícula'
            message(request, msg, error=True)
            return redirect('home:home')
        
        if not user:
            msg = 'não foi possível encontrar seu usuário, cadastre-se!!!'
            message(request, msg)                
            form = CreateForm(
                matricula = matricula
            )
            context = {
                'title': 'Cadastro',
                'form': form
            }
            url = 'home/cadastro.html'
            return render(request, url, context)
    
    if user.is_superuser:
        msg = 'Bem vindo administrador'
        try:
            data_super_user = DataUser.objects.get(
                owner = user
            )
        except DataUser.DoesNotExist:    
            form_data_user = DataUser(
                owner=user
            )
            form_data_user.save()
    else:
        msg = 'usuário encontrado!'
    message(request, msg, sucesss=True)
    context = {
        'title': 'login',
        'username': matricula,
        'horarios': days(),
        'form': Login(
            matricula
            )
        }
    url = 'home/login.html'
    return render(request, url, context=context)

@login_required(login_url="home:home")
def logout(request):
    auth.logout(request)
    message(request, 'Logout realizado', sucesss=True)
    return redirect('home:home')

home/views/matricula.py
from django.shortcuts import render, redirect
from home.models import Matriculas
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from home.views import message

@login_required(login_url="home:index")
def matricula(request):
    from home.models import Matriculas
    matriculas = Matriculas.objects.all()
    context = {
        'title': 'Matriculas',
        'matriculas': matriculas,
    }
    url = 'home/matricula.html'
    return render(request, url, context=context)

@login_required(login_url="home:index")
def create(request):
    context = {
        'title': 'Criando Matricula',
        }
    matricula = request.POST.get('matricula', '').strip()
    user = get_user(request)

    if matricula:
        matricula = Matriculas(
            matricula=matricula
        )
        if user:
            matricula.status = True
        matricula.save()
        message(request, 'Matricula Salva com Sucesso', sucesss=True)
    return redirect('home:matricula')

@login_required(login_url="home:index")
def update_matricula(request):
    context = {
        'title': 'atualizando Matricula',
        }
    
    matricula_antiga_id = request.POST.get('matricula_antiga_id', '').strip()
    matricula_nova = request.POST.get('matricula_nova', '').strip()
    if matricula_nova:
        print(matricula_nova)
    if matricula_antiga_id:
        print(matricula_antiga_id)
    return redirect('home:matricula')

@login_required(login_url="home:index")
def delete_matricula(request):
    
    matricula = request.POST.get('matricula', '').strip()
    
    delete_all = request.POST.get('delete_all', '').strip()
    
    confirmation = request.POST.get('confirmation', 'no').strip()
    
    matriculas = []
    if delete_all:
        matriculas = Matriculas.objects.all()
        
    if matricula:
        matricula = Matriculas.objects.filter(matricula=matricula)
        matricula.delete()
        message(request, f'Matricula {matricula} deletada com Sucesso', sucesss=True)
        return redirect('home:matricula')
    
    if confirmation != 'no':
        if matriculas:
            matriculas.delete()
        return redirect('home:matricula')

    context = {
        'title': 'Deletando Matricula',
        'confirmation': confirmation,
        'delete_all': delete_all,
        'matricula': matricula,
        'matriculas': matriculas,
    }

    return render(
        request, 'home/matricula.html', context=context
    )

home/templates/home/config.html
{% extends "home/index.html" %}
{% block content %}
    <div class="flex-column-space-between">
        <div class="flex-row">
            <a href="{% url 'home:matricula' %}"
            class='btn-select a-rodape item-padding margin'>
            AUTH</a>
            <a href="{% url 'home:usuarios' %}"
            class='btn-select a-rodape item-padding margin'>
            USERS</a>
            <a href="{% url 'home:dados' %}"
            class='btn-select a-rodape item-padding margin'>
            DADOS</a>
        </div>
        <div class="div-search border-white div-padding">
            <form action="{% url 'home:search_config' %}" method="get">
                <input type="text" name="q" id="search" class="form-search item-padding"
                placeholder="Search" autocomplete="off" value="{{search}}">
            </form>
        </div>
        {% if data %}
            <div class="flex-row overflow-x-auto">
                <table class="table-matricula div-padding">
                    <thead class="table-cabecalho">
                        <tr>
                            <th>matricula</th>
                            <th>nome</th>
                            <th>marcada</th>
                            <th>presente</th>
                            <th>cancelada</th>
                        </tr>
                    </thead>
                    <tbody class="table-body">
                        <!--for aqui-->
                        {% for aluno in data %}
                        <tr>
                            <td>{{aluno.usuario.username}}</td>
                            <td>{{aluno.usuario.first_name}}</td>
                            <td>{{aluno.monitorias_marcadas}}</td>
                            <td>{{aluno.monitorias_presentes}}</td>
                            <td>{{aluno.monitorias_canceladas}}</td> 
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="flex-row">
                {% if data.has_previous and data.has_next %}
                    <span class="flex-row-space-evenly">
                {% else %}
                    <span>
                {% endif %}
                    {% if data.has_previous %}
                        <a href="?page=1&q={{search}}">&laquo; first</a>
                        <a href="?page={{ data.previous_page_number }}&q={{search}}" class="next-previous">previous</a>
                    {% endif %}
        
                    <span class="current">
                        Page {{ data.number }} of {{ data.paginator.num_pages }}.
                    </span>
        
                    {% if data.has_next %}
                        <a href="?page={{ data.next_page_number }}&q={{search}}" class="next-previous">next</a>
                        <a href="?page={{ data.paginator.num_pages }}&q={{search}}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        {% else %}
            <p class="text-center table-matricula div-padding">Nenhuma monitoria encontrada</p>
        {% endif%}
    </div>
{% endblock content %}
{% block aside %}
    <div class="info div-padding">
        <h2 class="text-center item-padding legend">Dias da semana: </h2>
        <form action="{% url 'home:update_days' %}" method="post" class="flex-column border-white item-padding" enctype="multipart/form-data">
            {% csrf_token %}
            {% for day in daysweek %}
                <label for="{{day}}" class="flex-row-info item-padding">
                    <p class="legend">{{day}}</p>
                    {% if day in days %}
                        <input type="checkbox" name="{{day}}" id="{{day}}" value="{{day}}"checked>
                    {% else %}
                        <input type="checkbox" name="{{day}}" value="{{day}}" id="{{day}}">
                    {% endif %}
                </label>
            {% endfor %}
            <input type="submit" value="definir" class="btn-send">
        </form>
        <h2 class="text-center item-padding legend">Horas: </h2>
        <form action="{% url 'home:update_hours' %}" method="post" class="flex-column border-white item-padding" enctype="multipart/form-data">
            {% csrf_token %}
            <select class="hora" name="daysweek" id="daysweek">
                {% for day in days %}
                    <option value="{{day}}">
                        {{day}}
                    </option>
                {% endfor %}
            </select>
            <div class="flex-row">
                <input type="time" name="time_start" id="time_start" required>
                <input type="time" name="time_end" id="time_end" required>
            </div>
            <input type="submit" value="definir" class="btn-send">
        </form>
    </div>
{% endblock aside %}

home/templates/home/data.html
{% extends "home/index.html" %}
{% block content %}
    

{% endblock content %}
{% block aside %}{% endblock aside %}

home/templates/home/login.html
{% extends "home/index.html" %}
{% load static %}
{% block aside %}
<aside class="info div-padding">
    <div class="div-logo flex-row ">
        <a href="#" target="_blank">
            <img src="{% static 'home/images/logomarca-uerj.png' %}" alt="logo da uerj" class='logo'>
        </a>
    </div>
    <div>
        <form action="{% url 'home:login' %}" 
        class=" div-padding flex-column" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <label for="{{ field.id_for_label }}" class="flex-column item-padding">
                    {{ field }}
                </label>
                <div class="field-error">
                    {{field.errors}}
                </div>
            {% endfor %}
            <div class="item-padding flex-row-space-around">
                <input 
                type="submit" 
                value="login" 
                class="btn-send">
            </div>
        </form>
    </div>
</aside>
{% endblock aside %}

home/templates/home/matricula.html
{% extends "home/index.html" %}
{% block content %}
<div class="flex-column">
    <div class="flex-row">
        <div class="flex-column border-black margin-top-bottom">
            <h2 class="flex-row div-padding">CREATE</h2>
            <form method="POST" class="flex-column div-padding" action="{% url 'home:create' %}">
                {% csrf_token %}
                <label for="primeiro-nome" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">Matricula:</p>
                    <input type="text" id="primeiro-nome" name="matricula" class="form-cadastro" required>
                </label>
                <div class="flex-row-space-around item-padding">
                    <input type="submit" value="Cadastrar" class="btn-send">
                </div>
            </form>
        </div>
    </div>
    <div class="flex-row">
        <div class="flex-column border-black margin-top-bottom">
            <h2 class="flex-row div-padding">
                UDPATE
            </h2>
            <form 
            method="POST" 
            class="flex-column div-padding" 
            action="{% url 'home:update_matricula' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <select name="matricula_antiga_id" id="matricula" class="text-center">
                    {% for matricula in matriculas %}
                        <option value="{{matricula.id}}">
                            {{matricula.matricula}}
                        </option>
                    {% endfor %}
                </select>
                <label for="primeiro-nome" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">
                        Nova Matricula:
                    </p>
                    <input 
                    type="text" 
                    id="primeiro-nome" 
                    name="matricula_nova" class="form-cadastro" required maxlength="12">
                </label>
                <div class="flex-row-space-around item-padding">
                    <input type="submit" value="Atualizar" class="btn-send">
                </div>
            </form>
        </div>
    </div>
    <div class="flex-row">
        <div class="flex-column border-black margin-top-bottom">
            <h2 class="flex-row div-padding">DELETE</h2>
            <form method="POST" class="flex-column div-padding" action="{% url 'home:delete_matricula' %}">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                <label for="primeiro-nome" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">
                        Matricula:
                    </p>
                    <input type="text" id="primeiro-nome" name="matricula"
                    value="{{matricula}}"
                    class="form-cadastro">
                </label>
                <label for="delete_all" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">
                        Deletar tudo?
                    </p>
                    <input 
                    type="checkbox" 
                    id="delete_all" name="delete_all" 
                    class="form-cadastro"
                    {% if delete_all %}
                    checked
                    {% endif %}>
                </label>
                <div class="flex-row-space-around item-padding">
                    <input type="submit" value="Confirma?"
                    name='confirmation'
                    class="btn-send">
                </div>
                {% else %}
                <label for="primeiro-nome" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">
                        Matricula:
                    </p>
                    <input type="text" id="primeiro-nome" name="matricula" class="form-cadastro">
                </label>
                <label for="delete_all" class="flex-row-space-evenly item-padding">
                    <p class="legend-cadastro">
                        Deletar tudo?
                    </p>
                    <input 
                    type="checkbox" 
                    id="delete_all" name="delete_all" 
                    class="form-cadastro">
                </label>
                <div class="flex-row-space-around item-padding">
                    <input type="submit" value="Delete"
                    class="btn-send">
                </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block aside %}
    <div class="info div-padding">
        <p class="legend item-padding">Aqui você pode:</p>

        <p class="legend item-padding"> - viabilizar a criação da conta ao add. a matrícula!</p>
        
        <p class="legend item-padding">- atualizar a matricula!</p>

        <p class="legend item-padding"s>- deletar a matricula!</p>

    </div>
{% endblock aside %}

home/templates/home/update.html
{% extends "home/index.html" %}
{% block content %}
<div class="flex-row">
    <div class="flex-column">
        <h2 class="flex-row div-padding">UPDATE</h2>
        <form method="POST" class="flex-column div-padding" action="{% url 'home:update' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <label for="{{ field.id_for_label }}" class="flex-row-space-between item-padding">
                    <p class="legend-cadastro">
                        {{ field.label }}
                    </p>
                    {{ field }}
                </label>
                <div class="field-error">
                    {{field.errors}}
                </div>
            {% endfor %}
            <div class="flex-row-space-around item-padding">
                <a href="{% url 'home:password' %}"
                class='next-previous'>
                    alterar senha
                </a>
            </div>
            <div class="flex-row-space-around item-padding">
                <input type="submit" value="Atualizar" class="btn-send">
                <input type="reset" value="resetar" class="btn-send">
            </div>
        </form>
    </div>
</div>
{% endblock content %}
{% block aside %}
<div class="flex-column">    
    <h2 class="div-padding text-center italic">
        Informativos
    </h2>
    <p class="div-padding text-center italic">Aqui você atualiza o seu cadastro</p>
    <p class="div-padding text-center italic">É de extrema importância que você atualize os seus dados de imediato</p>
    <p class="div-padding text-center italic">Sua matrícula é inserida pelo monitor, os dados que podem ser alterados são somente esse ao lado</p>
    <p class="div-padding text-center legend-cadastro border-white italic error">Para cancelar sua conta é só desmarcar o box do ativo e atualizar</p>
</div>
{% endblock aside %}