home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    #uso livre.
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),

    path('monitorias/', views.monitoria, name='monitorias'),
    path('monitorias/search/', views.search_monitoria, name='search'),
    path('monitorias/update/<int:id>/', views.update_monitoria, name='update_monitoria'),

    #o usuário pode acessar.
    path('update/', views.update, name='update'),
    path('update/password/', views.password, name='password'),
    path('marcar_monitoria/', views.marcar_monitoria, name='marcar_monitoria'),

    #somente o super-user pode acessá-lo.
    path('data/', views.dados, name='dados'),
    path('config/', views.config, name='config'),
    path('config/search/', views.search_config, name='search_config'),
    path('config/update-days/', views.update_days, name='update_days'),
    path('config/update-hours/', views.update_hours, name='update_hours'),
    path('config/matricula/', views.matricula, name='matricula'),
    path('config/matricula/create', views.create, name='create'),
    path('config/matricula/update', views.update_matricula, name='update_matricula'),
    path('config/matricula/delete', views.delete_matricula, name='delete_matricula'),
    path('config/usuarios', views.usuarios, name='usuarios'),
    path('config/usuarios/search', views.search_usuarios, name='search_usuarios'),    
    path('config/usuarios/update', views.update_usuarios, name='update_usuarios'),
]


#TODO: 
# ------------OK 1 - disponibilizar o delete da conta do próprio usuário.


# ------------OK 2 - Montar view para expor ao usuário os dias que a monitoria pode ser marcada.
# ------------OK 5 - inserir o filtro de dados datetime.now para o search_monitorias
# ------------OK 6 - retirar o aside para o admin
# ------------OK 8 - disponibilizar para o usuário somente os dias da semana que ele possui marcação de horario na tabela monitoria;
# ------------OK 9 - requerer login para a view monitoria
# ------------OK 10 - admin não pode marcar monitoria, alterar o aside, mostrar todas as monitoria marcadas para hoje no aside  


# ------------OK 3 - atualizar o model de DataUser: inserir o atributo monitorias_ausentes
# ------------OK 11 - add telefone ao campo de updates
# 12 - add telefone ao campo de cadastro

# ------------OK 13 - add status ao models Monitorias
# ------------OK 14 - add alteração de status para as monitorias do dia e antepassadas
# 15 - vincular os campos de datauser ao models monitoria
# 16 - alterar a view update_monitorias para realizar o TODO n° 14
# 7 - inserir regra de negócio: mais de 3 moonitorias ausentes sem aviso prévio, o usuario será suspenso do sistema
# 17 - Refatorar o cadastro
# 18 - Inserir o campo de recuperar senha
# 19 - add hora ao marcar monitoria
# ------------OK 20 - ao criar o cadastro, criar o datauser

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls'), name='home'),    
]

home/views/cadastro.py
from django.shortcuts import render, redirect
from home.forms.update_create_form import CreateForm
from home.views import message
from home.models import DataUser, Matriculas
def cadastro(request):

    if request.method == 'POST':
        form = CreateForm(
            request.POST
        )
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            data_user = DataUser(owner=user)
            data_user.phone = form.cleaned_data['phone']
            data_user.save()
            matricula = Matriculas.objects.get(
                matricula=form.cleaned_data['username']
            )
            matricula.status = True
            matricula.save()

            form.save()
            message(request, 'Cadastro realizado com sucesso!', sucesss=True)
            return redirect('home:home')
        message(request, 'Atente-se aos requisitos!!!')
        context = {
        'title': 'Cadastro',
        'form': form,
        }
        url = 'home/cadastro.html'
        return render(request, url, context=context)

home/views/config.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from home.models import DataUser, Horas, Days
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from home.views.index import message
from home.views.index import daysweek

@login_required(login_url="home:home")
def update_hours(request):
    day = request.POST.get('daysweek', '').strip()
    time_start = request.POST.get('time_start', '').strip()
    time_end = request.POST.get('time_end', '').strip()
    if not day or not time_start or not time_end:
        message(request, 'Preencha todos os campos', error=True)
        return redirect('home:config')
    try:
        day = Days.objects.get(day=day)
    except Days.DoesNotExist:
        message(request, 'Dia não encontrado', error=True)
        return redirect('home:config')
    try:
        horas = Horas.objects.filter(
        day__day=day
        )
        for hora in horas:
            hora.delete()
    except Horas.DoesNotExist:
        ...
        
    horas_start = Horas(
        day=day,
        time=time_start
    )
    horas_start.save()
    horas_final = Horas(
        day=day,
        time=time_end
    )
    horas_final.save()
    return redirect('home:config')

@login_required(login_url="home:home")
def update_days(request):
    days = request.POST
    dias_cadastrados = Days.objects.all()
    dias_cadastrados.delete()
    time_start = request.POST.get('time_start', '07:00:00').strip()
    time_end = request.POST.get('time_end', '12:00:00').strip()
    for key, value in days.items():
        if key == 'csrfmiddlewaretoken':
            continue
        day = Days(day=value)
        day.save()
        horas_start = Horas(
            day=day,
            time=time_start
        )
        horas_start.save()
        horas_final = Horas(
            day=day,
            time=time_end
        )
        horas_final.save()
    return redirect('home:config')

@login_required(login_url="home:home") 
def search_config(request):

    search_value = str(request.GET.get('q', '')).strip()
    if not search_value:
        redirect('home:config')

    data_user = DataUser.objects.filter(
        Q(owner__username__icontains=search_value) |
        Q(owner__first_name__icontains=search_value) |
        Q(owner__last_name__icontains=search_value)
    )
    days = Days.objects.all()
    horas = Horas.objects.all().order_by('day')
    data = [{
        "usuario": user.owner, 
        "monitorias_presentes": user.monitorias_presentes, 
        "monitorias_marcadas": user.monitorias_marcadas} 
        for user in data_user if user.is_superuser == False
        ]
    hr = [
        {"time": h.time, "day": h.day.day} 
        for h in horas
        ]
    pagination = Paginator(data, 10)
    page_number = request.GET.get("page")
    data = pagination.get_page(page_number)
    context = {
        'title': f'Configurações-{search_value}',
        'data': data,
        'search': search_value,
        'daysweek': daysweek,
        'days': [str(dia).strip() for dia in days],
        'horas': hr,
    }
    url = 'home/config.html'
    return render(request, url, context=context)

@login_required(login_url="home:home") 
def config(request):

    data_user = DataUser.objects.all()
    days = Days.objects.all()

    horas = Horas.objects.all().order_by('day')
    data = [{
        "usuario": user.owner, 
        "monitorias_presentes": user.monitorias_presentes, 
        "monitorias_marcadas": user.monitorias_marcadas} 
        for user in data_user if user.owner.is_superuser == False
        ]
    hr = [{"time": h.time, "day": h.day.day} for h in horas]

    pagination = Paginator(data, 10)
    page_number = request.GET.get("page")
    data = pagination.get_page(page_number)

    context = {
        'title': 'Configurações',
        'data': data,
        'daysweek': daysweek,
        'days': [str(dia).strip() for dia in days],
        'horas': hr,
    }
    
    url = 'home/config.html'
    return render(request, url, context=context)

home/views/dados.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from home.models import User
from datetime import datetime
from django.db.models import Q
from django.core.paginator import Paginator

def dados(request):

    context = {
        'title': 'Estatísticas',
        'data': [],
    }
    url = 'home/data.html'
    return render(request, url, context=context)

home/views/index.py
from django.shortcuts import render
from home.models import Monitorias, Horas
from django.db.models import Q
from itertools import groupby
daysweek = [
    'Segunda-feira',
    'Terça-feira',
    'Quarta-feira',
    'Quinta-feira',
    'Sexta-feira',
]

LIM_PART_MONITORIA = 5

def monitorias_marcadas_usuario(user):
    import datetime
    from datetime import timedelta, datetime
    data = Monitorias.objects.filter(
        Q(owner=user) & 
        Q(status__icontains='Marcada') &
        Q(date__range=(
            datetime.now(), 
            datetime.now() + timedelta(days=7)
            )
        )
    )
    return data

def monitorias_marcadas_monitor():
    import datetime
    from datetime import datetime 
    data = Monitorias.objects.filter(
        Q(date__range=(datetime.now(), datetime.now())) &
        Q(status__icontains='Marcada')
    )
    return data

def free_days_next_monitorias():
    import datetime
    from datetime import datetime, timedelta
    data = Monitorias.objects.filter(
        Q(date__range=(datetime.now() + timedelta(1), datetime.now() + timedelta(days=7))) &
        Q(status__icontains='Marcada')

        )
    monitorias = groupby(sorted([
        {'date': item.date, 'user': item.owner.username} for item in data], key=lambda date: date['date']
        ), key=lambda date: date['date'])
    
    daysweek_monitoria = [daysweek.index(day['dayweek']) for day in days()]
    next_seven_days = set([
        (datetime.now() + timedelta(days=i)).date() 
        for i in range(1, 8) 
        if (datetime.now() + timedelta(days=i)).weekday() in daysweek_monitoria
        ])
    monitorias = set([item[0] for item in monitorias 
                  if len(list(item[1])) >= LIM_PART_MONITORIA
                  and item[0].weekday() in daysweek_monitoria
                  ])
    monitorias = sorted(list(next_seven_days - monitorias))
    return monitorias
    
def message(request, msg: str, sucesss=False, error=False):
    from django.contrib import messages
    if sucesss:
        return messages.success(request, msg)
    if error:
        return messages.error(request, msg)

    return messages.warning(request=request, message=msg)

def days():
    horarios = Horas.objects.all()
    weekday = {}
    data = [{"hora": item.time, 'day': item.day.day} for item in horarios]
    for item in data:
        if item['day'] not in weekday.keys():
            weekday[item['day']] = [item['hora']]
            continue
        weekday[item['day']].append(item['hora'])
    data = [{"dayweek": key, "time_start": str(value[0]), "time_final": str(value[-1])} for key, value in weekday.items()]
    return data

def index(request):

    context = {
        'title': 'HOME',
        'horarios': days(),
    }
    url = 'home/index.html'
    return render(request, url, context=context)

home/views/login.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from home.forms.login import Login
from home.forms.update_create_form import CreateForm
from django.contrib.auth.models import User
from django.db.models import Q
from home.models import DataUser, Matriculas
from home.views import days, message
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth 
from django.contrib.auth.decorators import login_required

def login(request):
    
    matricula = str(request.POST.get('matricula', '')).strip()
    password = request.POST.get('password', '')
    if password:
        form_auth = AuthenticationForm(
            request, data=request.POST)
        form = Login(
            matricula,
            request.POST
        )
        if form_auth.is_valid():
            user = form_auth.get_user()
            auth.login(request, user)
            message(request, 'Login realizado', sucesss=True)
            context = {
            'title': 'Home',
            'horarios': days(),
            'form': form,
            }
            url = 'home/index.html'
            return render(request, url, context=context)
        
        message(request, 'Login inválido, seu usuário pode estar inativo', error=True)
        context = {
            'title': 'login',
            'horarios': days(),
            'form': form,
        }
        url = 'home/login.html'
        return render(request, url, context=context)

    if len(matricula) != 12:
        message(request, 'Matrícula inválida', error=True)
        return redirect('home:home')

    if matricula:

        try:
            matriculas_cadastradas = Matriculas.objects.get(matricula = matricula)
        except Matriculas.DoesNotExist:
            matriculas_cadastradas = None
        
        try:
            user = User.objects.get(username= matricula)
            if not user.is_active:
                message(request, 'Usuário inativo', error=True)
                return redirect('home:home')    
        except User.DoesNotExist:
            user = None
        
        if not matriculas_cadastradas and not user:
            msg ='Não foi possível encontrar sua matrícula'
            message(request, msg, error=True)
            return redirect('home:home')
        
        if not user:
            msg = 'não foi possível encontrar seu usuário, cadastre-se!!!'
            message(request, msg)                
            form = CreateForm(
                matricula = matricula
            )
            context = {
                'title': 'Cadastro',
                'form': form
            }
            url = 'home/cadastro.html'
            return render(request, url, context)
    
    if user.is_superuser:
        msg = 'Bem vindo administrador'
        try:
            data_super_user = DataUser.objects.get(
                owner = user
            )
        except DataUser.DoesNotExist:    
            form_data_user = DataUser(
                owner=user
            )
            form_data_user.save()
    else:
        msg = 'usuário encontrado!'
    message(request, msg, sucesss=True)
    context = {
        'title': 'login',
        'username': matricula,
        'horarios': days(),
        'form': Login(
            matricula
            )
        }
    url = 'home/login.html'
    return render(request, url, context=context)

@login_required(login_url="home:home")
def logout(request):
    auth.logout(request)
    message(request, 'Logout realizado', sucesss=True)
    return redirect('home:home')

home/views/matricula.py
from django.shortcuts import render, redirect
from home.models import Matriculas
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from home.views import message

@login_required(login_url="home:index")
def matricula(request):
    from home.models import Matriculas
    matriculas = Matriculas.objects.all()
    context = {
        'title': 'Matriculas',
        'matriculas': matriculas,
    }
    url = 'home/matricula.html'
    return render(request, url, context=context)

@login_required(login_url="home:index")
def create(request):
    context = {
        'title': 'Criando Matricula',
        }
    matricula = request.POST.get('matricula', '').strip()
    user = get_user(request)

    if matricula:
        matricula = Matriculas(
            matricula=matricula
        )
        if user:
            matricula.status = True
        matricula.save()
        message(request, 'Matricula Salva com Sucesso', sucesss=True)
    return redirect('home:matricula')

@login_required(login_url="home:index")
def update_matricula(request):
    context = {
        'title': 'atualizando Matricula',
        }
    
    matricula_antiga_id = request.POST.get('matricula_antiga_id', '').strip()
    matricula_nova = request.POST.get('matricula_nova', '').strip()
    if matricula_nova:
        print(matricula_nova)
    if matricula_antiga_id:
        print(matricula_antiga_id)
    return redirect('home:matricula')

@login_required(login_url="home:index")
def delete_matricula(request):
    
    matricula = request.POST.get('matricula', '').strip()
    
    delete_all = request.POST.get('delete_all', '').strip()
    
    confirmation = request.POST.get('confirmation', 'no').strip()
    
    matriculas = []
    if delete_all:
        matriculas = Matriculas.objects.all()
        
    if matricula:
        matricula = Matriculas.objects.filter(matricula=matricula)
        matricula.delete()
        message(request, f'Matricula {matricula} deletada com Sucesso', sucesss=True)
        return redirect('home:matricula')
    
    if confirmation != 'no':
        if matriculas:
            matriculas.delete()
        return redirect('home:matricula')

    context = {
        'title': 'Deletando Matricula',
        'confirmation': confirmation,
        'delete_all': delete_all,
        'matricula': matricula,
        'matriculas': matriculas,
    }

    return render(
        request, 'home/matricula.html', context=context
    )

home/templates/home/partials/aside.html
{% load static %}
{% if not user.is_authenticated %}
    <aside class="info div-padding">
        <div class="div-logo flex-row ">
            <a href="#" target="_blank">
                <img src="{% static 'home/images/logomarca-uerj.png' %}" alt="logo da uerj" class='logo'>
            </a>
        </div>
        <form action="{% url 'home:login' %}" class=" div-padding flex-column" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="matricula" class="flex-column item-padding">
                <input type="text" name="matricula" id="matricula" required autocomplete="off" class="form" 
                placeholder="matrícula"
                minlength=12
                maxlength=12>
            </label>  
            <p name="info" id="prev_login"class='legend item-padding'>Digite sua matrícula para ir à página de login</p>
            <div class="item-padding flex-row-space-around">
                <input type="submit" value="ir" class="btn-send">
            </div>
        </form>
    </aside>
{% else %}
<aside class="info div-padding">
    <div class="div-logo flex-row ">
        <a href="#" target="_blank">
            <img src="{% static 'home/images/logomarca-uerj.png' %}" alt="logo da uerj" class='logo'>
        </a>
    </div>
    {% if not user.is_superuser %}
    <form action="{% url 'home:marcar_monitoria' %}" class=" div-padding flex-column" method="POST" enctype="multipart/form-data">
        <p class="legend flex-row item-padding  ">
            Marcar Monitoria:
        </p>
        {% csrf_token %}
        <label for="date" class="flex-column item-padding">
            <input type="date" name="date" id="date" placeholder="Select a date" class="form">
        </label>
        <!--<label for="text" class="flex-column item-padding">
            <textarea name="text" id="text" cols="30" rows="5"placeholder="Digite algo que deseje informar ao monitor...."></textarea>
        </label>-->
        <div class="item-padding flex-row-space-around">
            <input type="submit" value="marcar" class="btn-send">
        </div>
    </form>
        {% if not title == 'HOME' %}
            <p class="legend flex-row item-padding">Suas Próximas Monitorias:</p>
            <ul class='flex-column padding'>
                {% for item in monitorias_marcadas %}
                <li class="flex-column item-padding">
                    <p class="legend">{{item.date}}</p>
                </li>
                {% endfor %}
            </ul>    
        {% endif %}
    {% else %} 
        {% if not title == 'HOME' %}
            <p class="legend flex-row item-padding">Monitorias Hoje:</p>
            <ul class='flex-column'>
                {% for item in monitorias_marcadas %}
                <li class="item-padding">
                    <a href="{% url "home:update_monitoria" item.id %}"
                    class="flex-column border-white item-padding a-info">
                        <div class="flex-row-info">
                            <p class="legend">Nome:</p>
                            <p class="legend">
                                {{item.owner.first_name}}
                            </p>
                        </div>
                        <div class="flex-row-info">
                            <p class="legend">User:</p>
                             <p class="legend">
                                {{item.owner.username}}
                            </p>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>    
        {% endif %}
    {% endif %}
</aside>
{% endif %}

home/templates/home/partials/footer.html
{% load static %}
<footer class="rodape flex-row item-padding">
    <a href="https://github.com/DanielBrown1998/MON_UERJ_PROJECT" class="a-rodape" target="_blanck" rel="noopener">
        <img src="{% static 'home/images/minha_imagem.jpg' %}" alt="imagem do autor" class="img-rodape"> 
        Daniel Brown
    </a>
    <a href="https://www.cetreina.uerj.br/" class="a-rodape" target="_blank" rel="noopener">
        <img src='{% static "home/images/images.png" %}' alt="cetreina UERJ" class="img-rodape"> 
        Cetreina
    </a>
</footer>

home/templates/home/partials/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <title>{{title}}</title>
</head>

home/templates/home/partials/menu.html
{% if user.is_authenticated %}
    <nav class="nav-menu display-stick-top">
        <ul class="menu flex-row">
            <li class="item-menu"><a href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="item-menu">
                <a href="{% url 'home:monitorias' %}">
                    Monitorias
                </a>
            </li>    
            <li class="item-menu">
                <a href="{% url 'home:update' %}">
                    Update
                </a>
            </li>
            {% if user.is_superuser %}
                <li class="item-menu">
                    <a href="{% url 'home:config' %}">
                        Config
                    </a>
                </li>
            {% endif %}
            <li class="item-menu">
                <a href="{% url 'home:logout' %}">
                    Logout
                </a>
            </li>
        </ul>
    </nav>
{% endif %}